apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: fileupdatestest-component
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/dev-release-team-tenant/fileupdatestest/fileupdatestest-component@sha256:02180f4542e008801f250ba98b80b6afbb5e3c97265d368879610bfcb2bf89ca
        name: my-python
        resources: {}
status: {}
