apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fileupdatestest-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fileupdatestest-component
    app.kubernetes.io/part-of: fileupdatestest
  name: fileupdatestest-componentsl5n
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: fileupdatestest-component
    weight: null
status: {}
