apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fileupdatestest-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fileupdatestest-component
    app.kubernetes.io/part-of: fileupdatestest
  name: fileupdatestest-component
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: fileupdatestest-component
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: fileupdatestest-component
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/dev-release-team-tenant/fileupdatestest/fileupdatestest-component@sha256:02180f4542e008801f250ba98b80b6afbb5e3c97265d368879610bfcb2bf89ca
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
